### ISSUE TITLE
'setlua.bat' needs to change links for 'luac' as well as 'lua'

### ISSUE THREAD

**Issue by tbrunz** [Tieske/luawinmulti#19]
The section of the `setlua` batch file that sets up new 'lua' links, 

`copy "%myownpath%lua%1.exe" "%myownpath%lua.exe" /B /Y > NUL`

Needs to set up new links for `luac` in parallel.

I've attached a patched version of this batch file as a suggested fix (with `.txt` tacked onto the file name to make GitHub happy).

[setlua.bat.txt](https://github.com/Tieske/luawinmulti/files/4957234/setlua.bat.txt)

**Comment by Tieske** [comment]
Any chance you can send a PR?

**Comment by tbrunz** [comment]
Yes; I'll have to fork your repo, etc.  If not today, then in the next couple of days.

**Comment by tbrunz** [comment]
Done.

**Comment by Tieske** [comment]
implemented in #20
