### ISSUE TITLE
Path settings seem to be wrong in setlua.bat for Lua 5.1 and 5.2

### ISSUE THREAD

**Issue by oberhofer** [Tieske/luawinmulti#2]
1. Created a new install with "make install"
2. Called setlua.bat in a new console window
3. Tried to install a C module via luarocks (under Lua 5.1)
4. Loading C Module fails because Lua tries to load the DLL as a Lua-Module
5. Checked package.path and it contains ?.dll snippets
6. Looked up settings in setlua.bat and it seems LUA_PATH and LUA_CPATH are interchanged
7. Fixed following lines in setlua.bat:
   
   set LUA_PATH=;;%myownpath%..\share\lua\5.1\?.lua;%myownpath%..\share\lua\5.1\?\init.lua
   set LUA_CPATH=;;%myownpath%..\lib\lua\5.1\?.dll
   REM setup Lua paths for 5.2
   set LUA_PATH_5_2=;;%myownpath%..\share\lua\5.2\?.lua;%myownpath%..\share\lua\5.2\?\init.lua
   set LUA_CPATH_5_2=;;%myownpath%..\lib\lua\5.2\?.dll
8. Tested again, now C Module loads correctly

**Comment by Tieske** [comment]
Thx for the report. These are the offending lines https://github.com/Tieske/luawinmulti/blob/master/scripts/setlua.bat#L54-L59

Will fix them shortly

**Comment by Tieske** [comment]
fixed it!
