### ISSUE TITLE
Fatal Error in building Lua source

### ISSUE THREAD

**Issue by darmie** [Tieske/luawinmulti#6]
I am getting fatal errors while building Lua source. Some .lib and .obj files can't be linked.

```
link /nologo /DLL /out:lua53.dll  lapi.obj lcode.obj lctype.obj ldebug.obj ldo.obj ldump.obj lfunc.obj lgc.obj llex.obj lmem.obj lobject.obj lopcodes.obj lparser.obj lstate.obj lstring.obj ltable.obj ltm.obj lundump.obj lvm.obj lzio.obj lauxlib.obj  lbaselib.obj lbitlib.obj lcorolib.obj ldblib.obj liolib.obj lmathlib.obj loslib.obj lstrlib.obj ltablib.obj lutf8lib.obj loadlib.obj linit.obj
LINK : fatal error LNK1181: cannot open input file 'loadlib.obj'
link /nologo /out:lua.exe lua.obj lua53.lib
LINK : fatal error LNK1181: cannot open input file 'lua53.lib'
```

**Comment by darmie** [comment]
FIXED!!

I am using Visual Studio 2015 on a Windows 10 PC

Make sure you add these to your `Include` environment variable
![2016-02-20](https://cloud.githubusercontent.com/assets/848002/13196032/231a9686-d7c3-11e5-9461-d2070498e86a.png)

And add these to your `LIBPATH` or `LIB` environment variables
![2016-02-20 1](https://cloud.githubusercontent.com/assets/848002/13196047/7bf0624a-d7c3-11e5-9513-47da3942a125.png)

**Comment by Tieske** [comment]
@darmie You shouldn't have to, as long as you run it from the Visual Studio commandshell (or Win SDK commandshell).

**Comment by darmie** [comment]
Maybe you should include that in the Readme?

**Comment by Tieske** [comment]
like the 1st line here? https://github.com/Tieske/luawinmulti#command

I'll see that I make it more prominent :)

**Comment by darmie** [comment]
The compilers where in my path, but there were a lot of variables needed to
be in the path also, they are not automatically included in Windows 10.
`INCLUDE` , `LIBPATH` variables were not automatically set.

**Comment by Tieske** [comment]
are we on the same page here? Just to make sure; call it from the **Visual Studio commandshell**. That is; not a regular command prompt, but the specific one that comes with VS. That one runs a batch file and sets up the entire build environment, including all required environment variables .

The one that comes with Visual Studio is called `vcvarsall.bat` and the one from the SDK is `setenv.cmd` iirc.

If you use those, you should not need to set anything manually.

**Comment by darmie** [comment]
Alright thanks. I usually don't use Visual Studio even though I have it
installed. I guess that's why i didn't know I could do that.

**Comment by Tieske** [comment]
no worries, now you know :smile:
